/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.punktozaur.avro.loyalty;
@org.apache.avro.specific.AvroGenerated
public enum LoyaltyAccountCommandType implements org.apache.avro.generic.GenericEnumSymbol<LoyaltyAccountCommandType> {
  ADD_POINTS, SUBTRACT_POINTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LoyaltyAccountCommandType\",\"namespace\":\"pl.punktozaur.avro.loyalty\",\"symbols\":[\"ADD_POINTS\",\"SUBTRACT_POINTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
