/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package pl.punktozaur.avro.loyalty;
@org.apache.avro.specific.AvroGenerated
public enum LoyaltyAccountEventType implements org.apache.avro.generic.GenericEnumSymbol<LoyaltyAccountEventType> {
  POINTS_ADDED, POINTS_SUBTRACTED, POINTS_SUBTRACTION_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LoyaltyAccountEventType\",\"namespace\":\"pl.punktozaur.avro.loyalty\",\"symbols\":[\"POINTS_ADDED\",\"POINTS_SUBTRACTED\",\"POINTS_SUBTRACTION_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
